const ARRAY_KEYS = [
  [
    { className: 'Backquote', eng: { caseDown: '`', caseUp: '~' }, rus: { caseDown: 'ё', caseUp: 'Ё' } },
    { className: 'Digit1', eng: { caseDown: '1', caseUp: '!' }, rus: { caseDown: '1', caseUp: '!' } },
    { className: 'Digit2', eng: { caseDown: '2', caseUp: '@' }, rus: { caseDown: '2', caseUp: '"' } },
    { className: 'Digit3', eng: { caseDown: '3', caseUp: '#' }, rus: { caseDown: '3', caseUp: '№' } },
    { className: 'Digit4', eng: { caseDown: '4', caseUp: '$' }, rus: { caseDown: '4', caseUp: ';' } },
    { className: 'Digit5', eng: { caseDown: '5', caseUp: '%' }, rus: { caseDown: '5', caseUp: '%' } },
    { className: 'Digit6', eng: { caseDown: '6', caseUp: '^' }, rus: { caseDown: '6', caseUp: ':' } },
    { className: 'Digit7', eng: { caseDown: '7', caseUp: '&' }, rus: { caseDown: '7', caseUp: '?' } },
    { className: 'Digit8', eng: { caseDown: '8', caseUp: '*' }, rus: { caseDown: '8', caseUp: '*' } },
    { className: 'Digit9', eng: { caseDown: '9', caseUp: '(' }, rus: { caseDown: '9', caseUp: '(' } },
    { className: 'Digit0', eng: { caseDown: '0', caseUp: ')' }, rus: { caseDown: '0', caseUp: ')' } },
    { className: 'Minus', eng: { caseDown: '-', caseUp: '_' }, rus: { caseDown: '-', caseUp: '_' } },
    { className: 'Equal', eng: { caseDown: '=', caseUp: '+' }, rus: { caseDown: '=', caseUp: '+' } },
    { className: 'Backspace', eng: { caseDown: 'Backspace', caseUp: 'Backspace' }, rus: { caseDown: 'Backspace', caseUp: 'Backspace' } },
  ],

  [
    { className: 'Tab', eng: { caseDown: 'Tab', caseUp: 'Tab' }, rus: { caseDown: 'Tab', caseUp: 'Tab' } },
    { className: 'KeyQ', eng: { caseDown: 'q', caseUp: 'Q' }, rus: { caseDown: 'й', caseUp: 'Й' } },
    { className: 'KeyW', eng: { caseDown: 'w', caseUp: 'W' }, rus: { caseDown: 'ц', caseUp: 'Ц' } },
    { className: 'KeyE', eng: { caseDown: 'e', caseUp: 'E' }, rus: { caseDown: 'у', caseUp: 'У' } },
    { className: 'KeyR', eng: { caseDown: 'r', caseUp: 'R' }, rus: { caseDown: 'к', caseUp: 'К' } },
    { className: 'KeyT', eng: { caseDown: 't', caseUp: 'T' }, rus: { caseDown: 'е', caseUp: 'Е' } },
    { className: 'KeyY', eng: { caseDown: 'y', caseUp: 'Y' }, rus: { caseDown: 'н', caseUp: 'Н' } },
    { className: 'KeyU', eng: { caseDown: 'u', caseUp: 'U' }, rus: { caseDown: 'г', caseUp: 'Г' } },
    { className: 'KeyI', eng: { caseDown: 'i', caseUp: 'I' }, rus: { caseDown: 'ш', caseUp: 'Ш' } },
    { className: 'KeyO', eng: { caseDown: 'o', caseUp: 'O' }, rus: { caseDown: 'щ', caseUp: 'Щ' } },
    { className: 'KeyP', eng: { caseDown: 'p', caseUp: 'P' }, rus: { caseDown: 'з', caseUp: 'З' } },
    { className: 'BracketLeft', eng: { caseDown: '[', caseUp: '{' }, rus: { caseDown: 'х', caseUp: 'Х' } },
    { className: 'BracketRight', eng: { caseDown: ']', caseUp: '}' }, rus: { caseDown: 'ъ', caseUp: 'Ъ' } },
    { className: 'Backslash', eng: { caseDown: '\\', caseUp: '|' }, rus: { caseDown: '\\', caseUp: '/' } },
    { className: 'Delete', eng: { caseDown: 'Del', caseUp: 'Del' }, rus: { caseDown: 'Del', caseUp: 'Del' } },
  ],

  [
    { className: 'CapsLock', eng: { caseDown: 'CapsLock', caseUp: 'CapsLock' }, rus: { caseDown: 'CapsLock', caseUp: 'CapsLock' } },
    { className: 'KeyA', eng: { caseDown: 'a', caseUp: 'A' }, rus: { caseDown: 'ф', caseUp: 'Ф' } },
    { className: 'KeyS', eng: { caseDown: 's', caseUp: 'S' }, rus: { caseDown: 'ы', caseUp: 'Ы' } },
    { className: 'KeyD', eng: { caseDown: 'd', caseUp: 'D' }, rus: { caseDown: 'в', caseUp: 'В' } },
    { className: 'KeyF', eng: { caseDown: 'f', caseUp: 'F' }, rus: { caseDown: 'а', caseUp: 'А' } },
    { className: 'KeyG', eng: { caseDown: 'g', caseUp: 'G' }, rus: { caseDown: 'п', caseUp: 'П' } },
    { className: 'KeyH', eng: { caseDown: 'h', caseUp: 'H' }, rus: { caseDown: 'р', caseUp: 'Р' } },
    { className: 'KeyJ', eng: { caseDown: 'j', caseUp: 'J' }, rus: { caseDown: 'о', caseUp: 'О' } },
    { className: 'KeyK', eng: { caseDown: 'k', caseUp: 'K' }, rus: { caseDown: 'л', caseUp: 'Л' } },
    { className: 'KeyL', eng: { caseDown: 'l', caseUp: 'L' }, rus: { caseDown: 'д', caseUp: 'Д' } },
    { className: 'Semicolon', eng: { caseDown: ';', caseUp: ':' }, rus: { caseDown: 'ж', caseUp: 'Ж' } },
    { className: 'Quote', eng: { caseDown: '\'', caseUp: '"' }, rus: { caseDown: 'э', caseUp: 'Э' } },
    { className: 'Enter', eng: { caseDown: 'Enter', caseUp: 'Enter' }, rus: { caseDown: 'Enter', caseUp: 'Enter' } },
  ],

  [
    { className: 'ShiftLeft', eng: { caseDown: 'Shift', caseUp: 'Shift' }, rus: { caseDown: 'Shift', caseUp: 'Shift' } },
    { className: 'KeyZ', eng: { caseDown: 'z', caseUp: 'Z' }, rus: { caseDown: 'я', caseUp: 'Я' } },
    { className: 'KeyX', eng: { caseDown: 'x', caseUp: 'X' }, rus: { caseDown: 'ч', caseUp: 'Ч' } },
    { className: 'KeyC', eng: { caseDown: 'c', caseUp: 'C' }, rus: { caseDown: 'с', caseUp: 'С' } },
    { className: 'KeyV', eng: { caseDown: 'v', caseUp: 'V' }, rus: { caseDown: 'м', caseUp: 'М' } },
    { className: 'KeyB', eng: { caseDown: 'b', caseUp: 'B' }, rus: { caseDown: 'и', caseUp: 'И' } },
    { className: 'KeyN', eng: { caseDown: 'n', caseUp: 'N' }, rus: { caseDown: 'т', caseUp: 'Т' } },
    { className: 'KeyM', eng: { caseDown: 'm', caseUp: 'M' }, rus: { caseDown: 'ь', caseUp: 'Ь' } },
    { className: 'Comma', eng: { caseDown: ',', caseUp: '<' }, rus: { caseDown: 'б', caseUp: 'Б' } },
    { className: 'Period', eng: { caseDown: '.', caseUp: '>' }, rus: { caseDown: 'ю', caseUp: 'Ю' } },
    { className: 'Slash', eng: { caseDown: '/', caseUp: '?' }, rus: { caseDown: '.', caseUp: ',' } },
    { className: 'ArrowUp', eng: { caseDown: '▲', caseUp: '▲' }, rus: { caseDown: '▲', caseUp: '▲' } },
    { className: 'ShiftRight', eng: { caseDown: 'Shift', caseUp: 'Shift' }, rus: { caseDown: 'Shift', caseUp: 'Shift' } },
  ],

  [
    { className: 'ControlLeft', eng: { caseDown: 'Ctrl', caseUp: 'Ctrl' }, rus: { caseDown: 'Ctrl', caseUp: 'Ctrl' } },
    { className: 'MetaLeft', eng: { caseDown: 'Menu', caseUp: 'Menu' }, rus: { caseDown: 'Menu', caseUp: 'Menu' } },
    { className: 'AltLeft', eng: { caseDown: 'Alt', caseUp: 'Alt' }, rus: { caseDown: 'Alt', caseUp: 'Alt' } },
    { className: 'Space', eng: { caseDown: ' ', caseUp: ' ' }, rus: { caseDown: ' ', caseUp: ' ' } },
    { className: 'AltRight', eng: { caseDown: 'Alt', caseUp: 'Alt' }, rus: { caseDown: 'Alt', caseUp: 'Alt' } },
    { className: 'ArrowLeft', eng: { caseDown: '◄', caseUp: '◄' }, rus: { caseDown: '◄', caseUp: '◄' } },
    { className: 'ArrowDown', eng: { caseDown: '▼', caseUp: '▼' }, rus: { caseDown: '▼', caseUp: '▼' } },
    { className: 'ArrowRight', eng: { caseDown: '►', caseUp: '►' }, rus: { caseDown: '►', caseUp: '►' } },
    { className: 'ControlRight', eng: { caseDown: 'Ctrl', caseUp: 'Ctrl' }, rus: { caseDown: 'Ctrl', caseUp: 'Ctrl' } },
  ],
];

export default ARRAY_KEYS;
